# Cloud Build substitutions: use this same build config to push iamges for different env.
# steps:
# - name: 'gcr.io/cloud-builders/docker'
#   args: [ 'build', '-t', '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}', '.' ]
# images:
# - '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}'

steps:
# build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us-central1-docker.pkg.dev/flyntlok-test-project/nextjs-test-gke/nextjs-test-gke', '.' ]
# push container image
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'us-central1-docker.pkg.dev/flyntlok-test-project/nextjs-test-gke:latest' ]
# deploy container image to GKE
- name: 'gcr.io/cloud-builders/gke-deploy'
  args:
  - run
  - --filename='nextjs-test-gke'
  - --image='us-central1-docker.pkg.dev/flyntlok-test-project/nextjs-test-gke/nextjs-test-gke:latest'
  - --location='us-central1'
  - --cluster='nextjs-test-gke'
