# Cloud Build substitutions: use this same build config to push iamges for different env.
# steps:
# - name: 'gcr.io/cloud-builders/docker'
#   args: [ 'build', '-t', '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}', '.' ]
# images: 
# - '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}'

steps:
# build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: 
    - 'build'
    - '-t'
    - 'us-central1-docker.pkg.dev/flyntlok-test-project/nextjs-test-gke/nextjs-test-gke:$COMMIT_SHA'
    - '.'
# push container image
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'us-central1-docker.pkg.dev/flyntlok-test-project/nextjs-test-gke/nextjs-test-gke:$COMMIT_SHA' ]
# - name: 'gcr.io/cloud-builders/docker'
#   args: [ 'push', 'us-central1-docker.pkg.dev/flyntlok-test-project/nextjs-test-gke/nextjs-test-gke:latest' ]
# deploy image to GKE
- name: gcr.io/cloud-builders/kubectl
  args:
    - set
    - image
    - deployment/nextjs-test-gke
    - nextjs-test-gke=us-central1-docker.pkg.dev/flyntlok-test-project/nextjs-test-gke/nextjs-test-gke:$COMMIT_SHA
  env:
    - CLOUDSDK_COMPUTE_ZONE=us-central1
    - CLOUDSDK_CONTAINER_CLUSTER=nextjs-test-gke
