apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: nextjs-cbcd-pipeline
description: test project cicd pipeline
serialPipeline:
  stages:
  - targetId: nextjs-cbcd
  - targetId: nextjs-cbcd-prod
# suspended: true
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: nextjs-cbcd
description: testing development cluster
gke:
  cluster: projects/flyntlok-test-project/locations/us-central1-c/clusters/nextjs-cbcd
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: nextjs-cbcd-prod
description: testing production cluster
# requireApproval: true
gke:
  cluster: projects/flyntlok-test-project/locations/us-central1-c/clusters/nextjs-cbcd-prod