apiVersion: skaffold/v4beta2
metadata:
  name: nextjs-test-gke
build:
  artifacts:
    - image: us-central1-docker.pkg.dev/flyntlok-test-project/nextjs-test-gke/nextjs-test-gke
      docker:
        dockerfile: Dockerfile
manifests:
  kustomize:
    paths:
      - .
