# When a release is created, Google Cloud Deploy calls Skaffold to render your manifests.
# At deploy time, Google Cloud Deploy calls Skaffold again to apply those manifests to
#  deploy your application to each target in your progression. After deployment, Skaffold
#  performs health checks to monitor the target runtime for successful deployment.

apiVersion: skaffold/v2beta16
kind: Config
profiles:
  # Specify the profile name which you can run later using skaffold run -p <profilename>
  - name: nextjs-test-kustomize
    # build:
    #   artifacts:
    #     # Skaffold will use this as your image name and push it here after building
    #     - image: us-central1-docker.pkg.dev/flyntlok-test-project/nextjs-test-gke/nextjs-test-gke
    #     - 
    deploy:
      # In case we enable status check, this will be the timeout till which skaffold will wait
      # statusCheckDeadlineSeconds: 600
      # kustomize:
      #   paths:
      #     - .
      kubectl:
        # Location to our yaml files
        # Refer https://skaffold.dev/docs/references/yaml/ for more options
        manifests:
            - k8s/base/*.yaml
