apiVersion: skaffold/v2beta16
kind: Config
profiles:
  # Specify the profile name which you can run later using skaffold run -p <profilename>
  - name: nextjs-test-gke
    build:
      artifacts:
        # Skaffold will use this as your image name and push it here after building
        - image: us-central1-docker.pkg.dev/flyntlok-test-project/nextjs-test-gke/nextjs-test-gke
        context: nextjs-test-gke
    deploy:
      # In case we enable status check, this will be the timeout till which skaffold will wait
      statusCheckDeadlineSeconds: 600
      # Using kubectl as our deployer
      kubectl:
        # Location to our yaml files
        # Refer https://skaffold.dev/docs/references/yaml/ for more options
        manifests:
          - k8s/base/*.yml