apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: multi-prod
description: test for multiple prod clusters
requireApproval: true
multiTarget:
 targetIds: [ autopilot-cluster-1, autopilot-cluster-2 ]
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: nextjs-test-gke
description: testing development cluster
gke:
  cluster: projects/flyntlok-test-project/locations/us-central1/clusters/nextjs-test-gke
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: autopilot-cluster-1
description: testing production cluster
gke:
  cluster: projects/flyntlok-test-project/locations/us-central1/clusters/autopilot-cluster-1
---

# even a GKE in different location, target need to be created in the same location with delivery-pipeline
# accoring to: https://cloud.google.com/deploy/docs/regions#:~:text=Google%20Cloud%20Deploy%20instances%20can,to%20deploy%20to%20multiple%20regions.
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: autopilot-cluster-2
description: testing production cluster
gke:
  cluster: projects/flyntlok-test-project/locations/us-east1/clusters/autopilot-cluster-2