apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-test-app
spec:
  selector:
    matchLabels:
      app: nextjs-test-app
  replicas: 2
  template:
    metadata:
      labels:
        app: nextjs-test-app
    spec:
      containers:
        - name: nextjs-test-app
          image: sunny202305/nextjs-test-app
          ports:
           - containerPort: 3000