---
name: BUild and Push Nextjs Image to Google Cloud Platform.
on:
  push:
    branches: [ main ]
jobs:
  build-push-gcr:
    name: Build and Push Nextjs Image to GCP
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: nextjs-test-gke
      PROJECT_ID: flyntlok-test-project
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        project_id: ${{ env.PROJECT_ID }}
        export_default_credentials: true

    - name: Build Docker Image
      run: docker build -t $IMAGE_NAME:latest

    - name: Configure Docker Client

